apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: rancher-offline-docs
spec:
  selector:
    matchLabels:
      app: rancher-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher-offline-docs
    spec:
      containers:
        - name: rancher-offline-docs
          image: "{{ .Values.registry }}public/docs-rancher:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80