apiVersion: v1
kind: Service
metadata:
  name: rancher-offline-docs
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rancher-offline-docs